#Imagen de la raspberry pi 4 bullseye de 64 bits
FROM arm64v8/ubuntu:latest

#Dependencias
RUN apt-get update && apt-get install -y sudo ffmpeg libsm6 libxext6 git python3 python3-venv build-essential libssl-dev libffi-dev python3-dev python3-pip iproute2 && rm -rf /var/lib/apt/lists/*
RUN pip show flwr tensorflow opencv-python || pip install flwr tensorflow opencv-python

#Copiamos los ficheros necesarios
COPY start.sh /start.sh
COPY client.py /client.py

RUN chmod +x /start.sh
RUN chmod +x /client.py

CMD [ "./start.sh" ]
