# Imagen base más pequeña
FROM python:3.9-slim

# Instala las dependencias necesarias
RUN apt-get update && apt-get install -y --no-install-recommends \
        ffmpeg \
        libsm6 \
        libxext6 \
        git \
        libhdf5-dev \
        pkg-config \
        gcc \
    && rm -rf /var/lib/apt/lists/*

# Crea un entorno virtual y establece la variable de entorno PATH
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Instala las librerías de Python necesarias
RUN pip install --no-cache-dir --quiet \
        flwr \
        tensorflow \
        opencv-python

# Copia los archivos necesarios
COPY start.sh /start.sh
COPY client.py /client.py

# Cambia los permisos de los archivos
RUN chmod +x /start.sh /client.py

# Comando por defecto
CMD [ "./start.sh" ]
