version: "3.7"

volumes:
    prometheus-data:

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.2.2
    container_name: slave_node_exporter
    command:
    - '--path.rootfs=/host'
    restart: unless-stopped
    env_file:
    - .env
    pid: host
    expose:
    - 9100
    volumes:
    - '/:/host:ro,rslave'

  prometheus:
    image: prom/prometheus:v2.28.1
    container_name: slave_prometheus
    restart: unless-stopped
    env_file:
    - .env
    ports:
    - 9090:9090
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus-data:/prometheus

  cadvisor:
    image: zcube/cadvisor:latest
    container_name: slave_cAdvisor
    restart: unless-stopped
    env_file:
    - .env
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /dev/disk/:/dev/disk:ro
