global:
  scrape_interval:     5s # Interval at which metrics will be fetched
  evaluation_interval: 30s # Evaluate rules every 30 seconds, default is every minute
  
scrape_configs:

  - job_name: node_exporter
    static_configs:
    - targets: ['node_exporter:9100']

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - cadvisor:8080
  
